# =============================================================================
# host_vars/Ubuntu.yml – Хост-специфичные переменные для Vector
# =============================================================================

vector_host_ip: "111.88.243.109"

ansible_os_family: "Debian"
ansible_distribution: "Ubuntu"
ansible_distribution_version: "22.04"
