---
all:
  children:
    deb:
      hosts:
        ubuntu:
          ansible_connection: docker
    el:
      hosts:
        centos7:
          ansible_connection: docker
    fedora:
      hosts:
        fedora:
          ansible_connection: docker
    local:
      hosts:
        localhost:
          ansible_connection: local
  vars:
    ansible_user: root
